### ISSUE TITLE
 run_PI_RC 

### ISSUE THREAD

**Issue by aremazeilles** [VittorioFreiburg/COMTEST#3]
So I launch the following command:

```term
./run_pi_RC test_data/input/RCsway.csv out.csv
```
Iand I get generated the following information:

```term
more out.csv
setlingTime,1.84
peak,1.7
setlingMax,2.8
setlingMin,-0.8
overshoot,180
riseTime,1.66429
delayTime,1.67429
```

Do you confirm these valors? They ar enot equal to the one stored in the output folder.

According to the [documentation](https://eurobench.github.io/sofware_documentation/latest/pi_spec.html#_output_data), a PI should be stored as a `yaml` file. If all these fields are related to the same unique PI score in your case, the file could be of the following form:

```yaml
type: 'vector'
label: [setlingTime, peak, setlingMax, setlingMin, overshoot, riseTime, delayTime]
value: [1.84, 1.7, 2.8, -0.8, 180, 1.66429, 1.67429]
```   

Last comment, the input file (if the one I used is correct) is lacking an header column. Otherwise it is impossible to know what is inside it. Please have a look at the pre-processed format already proposed in the [documentation](https://eurobench.github.io/sofware_documentation/latest/data_format.html#sec:pre_processed_data). If none correspond to your information, you could use the generic `platformData.csv` format.
